name: Monthly Horse Update

on:
  schedule:
    - cron: "0 14 1 * *"
  workflow_dispatch:

jobs:
  send-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run horse update script
        run: ls -la && python ./monthly_horse_update.py
        env:
          RACING_API_USERNAME: ${{ secrets.RACING_API_USERNAME }}
          RACING_API_PASSWORD: ${{ secrets.RACING_API_PASSWORD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
